# -*- coding: utf-8 -*-
"""
Strictly block-supervised SAITS baseline.

Unlike run_pypots_baselines.py --train_with_block_mask, this script does NOT
rely on PyPOTS' default MIT dataset path, which re-applies MCAR masking during
training. Instead, it trains SAITS on the exact target_mask generated by this
project's ImputationDataset, so the supervised objective is aligned with the
block-missing evaluation protocol.
"""

import argparse
import copy
import math
import os
import time

import numpy as np
import torch
from torch.utils.data import DataLoader

from pypots.imputation import SAITS

from utils.seed import seed_everything
from utils.anchoring import anchor_fill_from_raw_pred
from utils.interp import linear_interp_torch
from data.loaders import load_csv_multivariate, split_and_scale
from data.datasets import ImputationDataset


def materialize_windows(ds: ImputationDataset, c: int):
    """Materialize deterministic val/test datasets for evaluation."""
    n = len(ds)
    l = ds.seq_len
    input_mask = np.zeros((n, l, c), dtype=np.float32)
    target_mask = np.zeros((n, l, c), dtype=np.float32)
    x_true = np.zeros((n, l, c), dtype=np.float32)

    for i in range(n):
        x_cat_i, x_true_i, target_i, _ = ds[i]
        input_mask[i] = x_cat_i[:, c:]
        target_mask[i] = target_i
        x_true[i] = x_true_i

    return input_mask, target_mask, x_true


def evaluate(name: str, imputed_norm: np.ndarray, x_true_norm: np.ndarray,
             input_mask: np.ndarray, target_mask: np.ndarray, scaler, c: int,
             anchor: bool = False):
    n, l, _ = imputed_norm.shape
    pred_inv = scaler.inverse_transform(imputed_norm.reshape(-1, c)).reshape(n, l, c)
    true_inv = scaler.inverse_transform(x_true_norm.reshape(-1, c)).reshape(n, l, c)

    if anchor:
        pred_filled = np.zeros_like(pred_inv)
        for b in range(n):
            pred_filled[b] = anchor_fill_from_raw_pred(
                true_inv[b], pred_inv[b], input_mask[b], anchor=True
            )
        pred_inv = pred_filled

    if anchor:
        pred_norm_metric = scaler.transform(pred_inv.reshape(-1, c)).reshape(n, l, c)
    else:
        pred_norm_metric = imputed_norm

    se = ((pred_inv - true_inv) ** 2) * target_mask
    ae = np.abs(pred_inv - true_inv) * target_mask
    std_se = ((pred_norm_metric - x_true_norm) ** 2) * target_mask
    std_ae = np.abs(pred_norm_metric - x_true_norm) * target_mask
    tot_cnt = target_mask.sum()

    obs_ae = np.abs(pred_inv - true_inv) * input_mask
    obs_mae = obs_ae.sum() / (input_mask.sum() + 1e-8)

    mse = se.sum() / (tot_cnt + 1e-8)
    mae = ae.sum() / (tot_cnt + 1e-8)
    rmse = math.sqrt(mse)
    std_mse = std_se.sum() / (tot_cnt + 1e-8)
    std_mae = std_ae.sum() / (tot_cnt + 1e-8)
    std_rmse = math.sqrt(std_mse)
    per_mae = ae.sum(axis=(0, 1)) / (target_mask.sum(axis=(0, 1)) + 1e-8)
    evaluate.last_std_mse = float(std_mse)

    tag = f"{name}{'+anchor' if anchor else ''}"
    print(f"[{tag}] masked-MSE={mse:.6f} | masked-RMSE={rmse:.6f} | masked-MAE={mae:.6f} (orig scale)")
    print(f"[{tag}] masked-STD-MSE={std_mse:.6f} | masked-STD-RMSE={std_rmse:.6f} | masked-STD-MAE={std_mae:.6f} (standardized scale)")
    print(f"[{tag}] observed-MAE={obs_mae:.6f} (orig scale, diagnostic only)")
    print(f"[{tag}] per-var MAE: {per_mae.tolist()}")
    return float(mse), float(rmse), float(mae), per_mae


def collect_imputation(model, loader: DataLoader, device: torch.device, c: int,
                       skeleton_fill_input: bool = False):
    model.eval()
    outs = []
    with torch.no_grad():
        for x_cat, _, _, _ in loader:
            x_cat = x_cat.to(device).float()
            x = x_cat[:, :, :c]
            missing_mask = x_cat[:, :, c:]
            if skeleton_fill_input:
                x = linear_interp_torch(x, missing_mask)
            results = model.forward(
                {"X": x, "missing_mask": missing_mask},
                diagonal_attention_mask=True,
                training=False,
            )
            outs.append(results["imputed_data"].detach().cpu().numpy())
    return np.concatenate(outs, axis=0)


def maybe_save(path: str, payload: dict):
    if path:
        torch.save(payload, path)
        print(f"[Save] {path}")


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--root_path", default="./data")
    p.add_argument("--data_path", default="ETTh1.csv")
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--seq_len", type=int, default=96)

    p.add_argument("--mask_mode", default="block",
                   choices=["block", "block_ratio", "point", "single_block", "partial", "mixed"])
    p.add_argument("--mask_ratio", type=float, default=0.4)
    p.add_argument("--block_len", type=int, default=24)
    p.add_argument(
        "--train_block_lens",
        nargs="+",
        type=int,
        default=None,
        help="Optional train-only block lengths sampled by ImputationDataset. Validation/test keep fixed block lengths.",
    )
    p.add_argument(
        "--val_block_len",
        type=int,
        default=None,
        help="Optional validation block length for checkpoint selection. Defaults to --block_len.",
    )
    p.add_argument(
        "--test_block_len",
        type=int,
        default=None,
        help="Optional test block length. Defaults to --block_len.",
    )
    p.add_argument(
        "--block_len_curriculum",
        default="none",
        choices=["none", "short_to_long", "three_phase"],
        help="Train-only curriculum over --train_block_lens.",
    )
    p.add_argument("--block_shared", action="store_true")
    p.add_argument(
        "--reproducible_epoch_mask",
        action="store_true",
        help="Resample train masks every epoch, but make them reproducible from (seed, epoch, idx).",
    )
    p.add_argument("--p_point", type=float, default=0.3)
    p.add_argument("--p_block", type=float, default=0.3)
    p.add_argument("--p_partial", type=float, default=0.4)
    p.add_argument("--point_ratio", type=float, default=0.03)
    p.add_argument("--partial_min_vars", type=int, default=2)
    p.add_argument("--partial_max_vars", type=int, default=4)

    p.add_argument("--epochs", type=int, default=30)
    p.add_argument("--patience", type=int, default=10)
    p.add_argument("--batch_size", type=int, default=64)
    p.add_argument("--lr", type=float, default=1e-3)
    p.add_argument("--weight_decay", type=float, default=0.0)
    p.add_argument("--grad_clip", type=float, default=1.0)
    p.add_argument("--device", default="cuda")
    p.add_argument("--anchor", action="store_true")
    p.add_argument("--save_path", default="")
    p.add_argument(
        "--skeleton_fill_input",
        action="store_true",
        help="Skeleton-aligned input adapter: fill missing values with the linear-interpolation "
             "skeleton (instead of zeros) before every SAITS forward pass, in training, "
             "validation, and test alike. missing_mask, the SAITS ORT/MIT losses, checkpoint "
             "selection, and evaluation are unchanged, so the only difference against the "
             "SAITS-blocksup baseline is the value content the network sees at missing positions.",
    )
    p.add_argument(
        "--var_weighted_loss",
        action="store_true",
        help="Fairness control: replace SAITS's default MAE reconstruction loss with the same "
             "per-variable variance-weighted masked MSE that SRI uses (weights = normalized "
             "train-split sigma^2). Neutralizes the metric-alignment confound where SRI targets "
             "original-scale MSE and baselines do not. Injected via SAITS customized_loss_func; "
             "pypots internals untouched.",
    )

    p.add_argument("--mse_mae_loss", action="store_true",
                   help="Equal-loss control: replace SAITS's masked MAE with the unweighted masked "
                        "MSE + MAE on standardized values that VA-SRI is trained with.")
    p.add_argument("--skip_test", action="store_true",
                   help="Stop after checkpoint selection; never evaluate the test split (for tuning).")
    p.add_argument("--select_std", action="store_true",
                   help="Select the checkpoint by standardized (not original-scale) validation MSE.")
    p.add_argument("--ema_decay", type=float, default=0.0,
                   help="Evaluate/select an exponential moving average of the weights (0 = off).")
    p.add_argument("--saits_n_layers", type=int, default=3)
    p.add_argument("--saits_d_model", type=int, default=128)
    p.add_argument("--saits_d_ffn", type=int, default=256)
    p.add_argument("--saits_n_heads", type=int, default=4)
    p.add_argument("--saits_d_k", type=int, default=32)
    p.add_argument("--saits_d_v", type=int, default=32)
    p.add_argument("--saits_dropout", type=float, default=0.1)
    p.add_argument("--saits_attn_dropout", type=float, default=0.0)
    p.add_argument("--saits_ort_weight", type=float, default=1.0)
    p.add_argument("--saits_mit_weight", type=float, default=1.0)

    args = p.parse_args()
    seed_everything(args.seed)
    args.patience = min(args.patience, max(1, args.epochs))

    device = torch.device(
        args.device if (args.device == "cpu" or torch.cuda.is_available()) else "cpu"
    )

    data_raw = load_csv_multivariate(args.root_path, args.data_path)
    train, val, test, scaler = split_and_scale(data_raw)
    c = train.shape[1]
    print(f"[Data] T={len(data_raw)} C={c} | train={len(train)} val={len(val)} test={len(test)}")
    print(f"[Device] {device}")

    val_block_len = args.val_block_len or args.block_len
    test_block_len = args.test_block_len or args.block_len
    print(
        f"[Block lengths] train={args.train_block_lens or [args.block_len]} "
        f"| val={val_block_len} | test={test_block_len} | curriculum={args.block_len_curriculum}"
    )
    if args.skeleton_fill_input:
        print("[SkeletonAlign] SAITS input missing values filled with the linear-interpolation skeleton")

    ds_kwargs = dict(
        seq_len=args.seq_len,
        fixed_seed=args.seed,
        mask_mode=args.mask_mode,
        mask_ratio=args.mask_ratio,
        block_shared=args.block_shared,
        p_point=args.p_point,
        p_block=args.p_block,
        p_partial=args.p_partial,
        point_ratio=args.point_ratio,
        partial_min_vars=args.partial_min_vars,
        partial_max_vars=args.partial_max_vars,
    )

    train_ds = ImputationDataset(
        train,
        mode="train",
        reproducible_epoch_mask=args.reproducible_epoch_mask,
        block_len=args.block_len,
        block_lens=args.train_block_lens,
        block_len_curriculum=args.block_len_curriculum,
        curriculum_epochs=args.epochs,
        **ds_kwargs,
    )
    val_ds = ImputationDataset(val, mode="val", block_len=val_block_len, **ds_kwargs)
    test_ds = ImputationDataset(test, mode="test", block_len=test_block_len, **ds_kwargs)

    train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True, num_workers=0)
    val_loader = DataLoader(val_ds, batch_size=args.batch_size, shuffle=False, num_workers=0)
    test_loader = DataLoader(test_ds, batch_size=args.batch_size, shuffle=False, num_workers=0)

    val_input_mask, val_target_mask, val_x_true = materialize_windows(val_ds, c)
    test_input_mask, test_target_mask, test_x_true = materialize_windows(test_ds, c)

    print(f"[Val windows] {len(val_ds)} | [Test windows] {len(test_ds)}")
    print(f"[Val target ratio] {val_target_mask.mean():.3f} | [Test target ratio] {test_target_mask.mean():.3f}")

    loss_func = None
    if args.var_weighted_loss:
        # Same per-variable weighting SRI uses: normalized train-split sigma^2.
        std2 = np.asarray(scaler.std, dtype=np.float32) ** 2
        std2 = std2 / (std2.mean() + 1e-8)
        w = torch.from_numpy(std2).to(device).view(1, 1, -1)

        def var_weighted_masked_mse(pred, target, mask):
            wl = w.to(device=pred.device, dtype=pred.dtype)
            m = mask.to(device=pred.device, dtype=pred.dtype)
            return (((pred - target) ** 2) * m * wl).sum() / ((m * wl).sum() + 1e-8)

        loss_func = var_weighted_masked_mse
        print("[VarWeightedLoss] SAITS trained with SRI-matched variance-weighted masked MSE")

    if args.mse_mae_loss:
        assert not args.var_weighted_loss, "--mse_mae_loss and --var_weighted_loss are exclusive"

        def masked_mse_mae(pred, target, mask):
            m = mask.to(device=pred.device, dtype=pred.dtype)
            n = m.sum() + 1e-8
            d = pred - target
            return ((d ** 2) * m).sum() / n + (d.abs() * m).sum() / n

        loss_func = masked_mse_mae
        print("[MseMaeLoss] SAITS trained with masked MSE + MAE (VA-SRI loss)")

    saits_kwargs = dict(
        n_steps=args.seq_len,
        n_features=c,
        n_layers=args.saits_n_layers,
        d_model=args.saits_d_model,
        d_ffn=args.saits_d_ffn,
        n_heads=args.saits_n_heads,
        d_k=args.saits_d_k,
        d_v=args.saits_d_v,
        dropout=args.saits_dropout,
        attn_dropout=args.saits_attn_dropout,
        ORT_weight=args.saits_ort_weight,
        MIT_weight=args.saits_mit_weight,
        batch_size=args.batch_size,
        epochs=args.epochs,
        patience=args.patience,
        device=device,
    )
    if loss_func is not None:
        saits_kwargs["customized_loss_func"] = loss_func
    saits = SAITS(**saits_kwargs)
    model = saits.model
    if loss_func is not None:
        # pypots' SAITS wrapper stores customized_loss_func on itself but does
        # NOT pass it into the core _SAITS module (model.py builds _SAITS
        # without it), and this runner trains via saits.model directly. Inject
        # the loss on the core module explicitly and verify it took effect so
        # a silent fallback to calc_mae is impossible.
        model.customized_loss_func = loss_func
        assert model.customized_loss_func is loss_func, "var-weighted loss injection failed"
        print("[VarWeightedLoss] injected into core _SAITS module (verified)")
    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    param_count = sum(p.numel() for p in model.parameters())
    trainable_param_count = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"[Params] total={param_count} | trainable={trainable_param_count}")

    best_val = float("inf")
    best_epoch = 0
    ema = (torch.optim.swa_utils.AveragedModel(
        model, multi_avg_fn=torch.optim.swa_utils.get_ema_multi_avg_fn(args.ema_decay))
        if args.ema_decay > 0 else None)
    scored = ema.module if ema is not None else model   # weights that are evaluated/selected
    best_state = copy.deepcopy(scored.state_dict())
    patience_left = args.patience
    train_start = time.perf_counter()

    for ep in range(1, args.epochs + 1):
        train_ds.set_epoch(ep - 1)
        model.train()
        total_loss = 0.0
        total_ort = 0.0
        total_mit = 0.0
        n_batches = 0

        for x_cat, x_true, target_mask, _ in train_loader:
            x_cat = x_cat.to(device).float()
            x_true = x_true.to(device).float()
            target_mask = target_mask.to(device).float()

            x = x_cat[:, :, :c]
            missing_mask = x_cat[:, :, c:]
            if args.skeleton_fill_input:
                x = linear_interp_torch(x, missing_mask)
            inputs = {
                "X": x,
                "missing_mask": missing_mask,
                "X_ori": x_true,
                "indicating_mask": target_mask,
            }

            results = model.forward(inputs, diagonal_attention_mask=True, training=True)
            loss = results["loss"]

            optimizer.zero_grad()
            loss.backward()
            if args.grad_clip > 0:
                torch.nn.utils.clip_grad_norm_(model.parameters(), args.grad_clip)
            optimizer.step()
            if ema is not None:
                ema.update_parameters(model)

            total_loss += float(loss.item())
            total_ort += float(results["ORT_loss"].item())
            total_mit += float(results["MIT_loss"].item())
            n_batches += 1

        val_imputed = collect_imputation(
            scored, val_loader, device, c, skeleton_fill_input=args.skeleton_fill_input
        )
        val_mse, _, _, _ = evaluate(
            "Val",
            val_imputed,
            val_x_true,
            val_input_mask,
            val_target_mask,
            scaler,
            c,
            anchor=False,
        )
        if args.select_std:
            val_mse = evaluate.last_std_mse

        print(
            f"[Train] Epoch {ep:03d} | loss={total_loss/max(1, n_batches):.6f} "
            f"| ort={total_ort/max(1, n_batches):.6f} | mit={total_mit/max(1, n_batches):.6f} "
            f"| val_mse={val_mse:.6f}"
        )

        if val_mse < best_val:
            best_val = val_mse
            best_epoch = ep
            best_state = copy.deepcopy(scored.state_dict())
            patience_left = args.patience
            if args.save_path:
                maybe_save(
                    args.save_path,
                    {
                        "epoch": ep,
                        "model": best_state,
                        "args": vars(args),
                        "best_val_mse": best_val,
                    },
                )
        else:
            patience_left -= 1
            if patience_left <= 0:
                print(f"[EarlyStop] no improvement for {args.patience} epochs, stopping at epoch {ep}")
                break

    scored.load_state_dict(best_state)
    model = scored
    print(f"[Timing] train_wall_seconds={time.perf_counter() - train_start:.3f}")
    print(f"[Best] epoch={best_epoch} | val_mse={best_val:.6f}")
    if args.skip_test:
        val_imputed = collect_imputation(
            model, val_loader, device, c, skeleton_fill_input=args.skeleton_fill_input
        )
        evaluate("BestVal", val_imputed, val_x_true, val_input_mask, val_target_mask, scaler, c, anchor=False)
        print("[SkipTest] test split not evaluated")
        return

    test_start = time.perf_counter()
    test_imputed = collect_imputation(
        model, test_loader, device, c, skeleton_fill_input=args.skeleton_fill_input
    )
    method_tag = "SAITS-blocksup"
    if args.skeleton_fill_input:
        method_tag += "-skelfill"
    if args.var_weighted_loss:
        method_tag += "-vw"
    if args.mse_mae_loss:
        method_tag += "-msemae"
    evaluate(method_tag, test_imputed, test_x_true, test_input_mask, test_target_mask, scaler, c, anchor=False)
    if args.anchor:
        evaluate(method_tag, test_imputed, test_x_true, test_input_mask, test_target_mask, scaler, c, anchor=True)
    test_wall = time.perf_counter() - test_start
    throughput = len(test_ds) / max(test_wall, 1e-8)
    print(f"[Timing] test_wall_seconds={test_wall:.3f} | throughput_windows_per_sec={throughput:.3f}")


if __name__ == "__main__":
    main()
